# xrp-ledger.toml file.
# Note: all fields and all sections are optional.

[METADATA]
modified = 2024-09-12T00:00:00.000Z
expires = 2026-12-31T00:00:00.000Z

[[VALIDATORS]]
public_key = "nHUDCZ6Tx8uk2Um5QwjsiDUQzpPZLnZ5cd3kfuAXjwLAJujVL5ER"
attestation = "C155DB4898B1DB0FA4EECCD897D2CB1AC3E6AAAB730A50EE563729553E6592964E6FAE0C87770B821E24F257BA40B5B63A1ABD1C9D9D6EFFCB71C302BA430803"
network = "main"
owner_country = "ca"
server_country = "gb"
unl = "https://ftsocan.com"

[[ACCOUNTS]]
address = "rhc4KWimzyK4e6Sqcg1c9RmGxg8egkoqeV"
desc = "FTSOCAN-owned address"

[[PRINCIPALS]]
name = "FTSOCAN" # Primary spec author
email = "info@ftsocan.com"

# End of file
